/* Local QQ Music styled prototype. No Tencent account or messaging API is connected. */
(()=>{
  'use strict';
  const friends=['小雨','阿哲','林一','妈妈'],key='yinli-qq-demo-v1',logo='./assets/brand/qq-music.png';
  const read=()=>{try{return {name:'',owner:'',messages:[],...JSON.parse(localStorage.getItem(key))};}catch{return{name:'',owner:'',messages:[]};}};
  const save=data=>{try{localStorage.setItem(key,JSON.stringify(data));return true;}catch{alert('消息存储空间不足，请缩短录音后重试。');return false;}};
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const cleanText=value=>String(value||'').replace(/（本机演示）|（好友消息示例，暂无礼物链接）/g,'');
  const time=value=>new Date(value||Date.now()).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});
  const avatar=name=>`<span class="qq-avatar" aria-hidden="true">${esc([...name][0]||'音')}</span>`;
  const modal=document.createElement('section');modal.id='qq-demo-modal';modal.className='qq-demo-modal';modal.hidden=true;document.body.append(modal);
  let activeContact='',activeGiftMessage=null,pendingShare=null,recording=null,recorded=null,stream=null;
  function shell(content,wide=false){modal.innerHTML=`<div class="qq-demo-card ${wide?'qq-chat-card':''}" role="dialog" aria-modal="true" aria-label="QQ音乐好友消息"><button class="qq-demo-close" type="button" aria-label="关闭">×</button><div class="qq-demo-brand"><img class="qq-logo" src="${logo}" alt=""><span>QQ音乐好友</span></div>${content}</div>`;modal.hidden=false;}
  function login(){shell(`<div class="qq-login"><h2>连接好友消息</h2><p>填写昵称，进入你的好友消息。</p><label>你的昵称<input id="qq-demo-name" maxlength="20" autocomplete="nickname" placeholder="输入昵称"></label><button class="qq-demo-primary" data-qq-action="login">进入消息</button><small>当前设备中的好友消息会保留在浏览器里。</small></div>`);modal.querySelector('#qq-demo-name')?.focus();}
  const conversation=(data,name)=>data.messages.filter(item=>(item.from===data.name&&item.to===name)||(item.to===data.name&&item.from===name));
  function contacts(data){return [...new Set([data.owner,...friends,...data.messages.flatMap(item=>[item.from,item.to])])].filter(name=>name&&name!==data.name).sort((a,b)=>(conversation(data,b).at(-1)?.at||0)-(conversation(data,a).at(-1)?.at||0));}
  function contactRows(data){return contacts(data).map(name=>{const last=conversation(data,name).at(-1),preview=last?.link?'[音礼] '+cleanText(last.text||'打开一份音礼'):last?.audio?'[语音] '+cleanText(last.text||'一段回声'):cleanText(last?.text)||'开始一段对话';return `<button type="button" class="qq-contact ${activeContact===name?'is-active':''}" data-qq-contact="${esc(name)}">${avatar(name)}<span class="qq-contact-copy"><b>${esc(name)}</b><small>${esc(preview)}</small></span><time>${last?time(last.at):''}</time></button>`;}).join('');}
  function messageRows(data,name){const messages=conversation(data,name);if(!messages.length)return '<p class="qq-chat-empty">还没有消息。发一句话，开始对话吧。</p>';return messages.map(message=>{const own=message.from===data.name,body=cleanText(message.text);return `<div class="qq-bubble-row ${own?'own':''}">${avatar(message.from)}<div class="qq-bubble"><small>${esc(message.from)} · ${time(message.at)}</small>${body?`<p>${esc(body)}</p>`:''}${message.link?`<button class="qq-gift-link" type="button" data-qq-open="${esc(message.id)}">打开这份音礼 <span>↗</span></button>`:''}${message.audio?`<audio controls src="${esc(message.audio)}"></audio>`:''}</div></div>`;}).join('');}
  function inbox(contact=activeContact){const data=read();if(!data.name){login();return;}data.owner||=data.name;if(!data.messages.length){data.messages.push({id:'welcome',from:'小雨',to:data.owner,at:Date.now()-3600000,text:'嗨，最近有什么想分享的音乐和记忆？'});save(data);}const names=contacts(data);activeContact=names.includes(contact)?contact:(names[0]||'');const identities=[...new Set([data.owner,...friends])];shell(`<div class="qq-chat-head"><div><h2>消息</h2><small>与好友分享声音和记忆</small></div><label class="qq-identity">${avatar(data.name)}<select id="qq-demo-identity" aria-label="切换账号">${identities.map(name=>`<option value="${esc(name)}" ${name===data.name?'selected':''}>${esc(name)}</option>`).join('')}</select></label></div><div class="qq-chat-layout ${contact?'show-conversation':''}"><aside class="qq-contact-pane" aria-label="好友列表"><div class="qq-pane-title">好友</div>${contactRows(data)}</aside><div class="qq-conversation-pane">${activeContact?`<header><button class="qq-mobile-back" type="button" data-qq-action="list" aria-label="返回消息列表">←</button>${avatar(activeContact)}<b>${esc(activeContact)}</b></header><div class="qq-conversation-scroll">${messageRows(data,activeContact)}</div><div class="qq-compose"><textarea id="qq-chat-text" rows="2" aria-label="消息内容" placeholder="写一条消息…"></textarea><div><button type="button" data-qq-action="record">录音</button><span id="qq-record-status" aria-live="polite"></span><button class="qq-demo-primary" type="button" data-qq-action="send">发送</button></div></div>`:'<div class="qq-chat-empty">选择一位好友，查看消息</div>'}</div></div><div class="qq-local-note">当前设备的消息</div>`,true);const scroll=modal.querySelector('.qq-conversation-scroll');if(scroll)scroll.scrollTop=scroll.scrollHeight;}
  function shareBox(){const target=document.getElementById('yinli-share-link');if(!target||document.getElementById('qq-share-demo'))return;const box=document.createElement('div');box.id='qq-share-demo';box.className='qq-share-demo';box.innerHTML=`<div class="qq-share-heading"><img class="qq-logo" src="${logo}" alt=""><b>发送给 QQ 音乐好友</b></div><div class="qq-share-row"><label><span class="sr-only">选择好友</span><select id="qq-demo-friend">${friends.map(name=>`<option>${name}</option>`).join('')}</select></label><button type="button" data-qq-action="share">发送</button></div><small id="qq-share-status">选择好友，分享这份音礼</small>`;target.after(box);}
  function share(){const link=document.getElementById('yinli-share-link')?.value,to=document.getElementById('qq-demo-friend')?.value||friends[0];if(!link)return;const data=read();if(!data.name){pendingShare={link,to};login();return;}data.messages.push({id:crypto.randomUUID(),from:data.name,to,at:Date.now(),text:'我给你送来一份音礼',link});if(save(data)){activeContact=to;inbox(to);}}
  function send(){const text=modal.querySelector('#qq-chat-text')?.value.trim()||'';if(!text&&!recorded){modal.querySelector('#qq-chat-text')?.focus();return;}const data=read();if(!data.name||!activeContact)return;data.messages.push({id:crypto.randomUUID(),from:data.name,to:activeContact,at:Date.now(),text:text||'一段语音回声',audio:recorded||''});if(save(data)){recorded=null;inbox(activeContact);}}
  function echo(){const data=read();if(!data.name){login();return;}inbox(activeGiftMessage?.from||data.owner||friends[0]);modal.querySelector('#qq-chat-text')?.focus();}
  async function toggleRecord(){const button=modal.querySelector('[data-qq-action="record"]'),status=modal.querySelector('#qq-record-status');if(recording){recording.stop();button.textContent='录音';return;}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){status.textContent='当前浏览器不支持录音';return;}try{stream=await navigator.mediaDevices.getUserMedia({audio:true});const chunks=[];recording=new MediaRecorder(stream);recording.ondataavailable=event=>{if(event.data.size)chunks.push(event.data);};recording.onstop=()=>{const blob=new Blob(chunks,{type:recording.mimeType||'audio/webm'});stream.getTracks().forEach(track=>track.stop());recording=null;const reader=new FileReader();reader.onload=()=>{recorded=String(reader.result);status.textContent='语音已就绪';};reader.readAsDataURL(blob);};recording.start();button.textContent='停止';status.textContent='正在录音…';setTimeout(()=>{if(recording){recording.stop();button.textContent='录音';}},30000);}catch{status.textContent='没有获得麦克风权限';}}
  document.addEventListener('click',event=>{if(event.target===modal||event.target.closest('.qq-demo-close')){modal.hidden=true;return;}if(event.target.closest('.qq-demo-trigger')){inbox();return;}if(event.target.id==='qq-echo-button'){echo();return;}const contact=event.target.closest('[data-qq-contact]');if(contact){inbox(contact.dataset.qqContact);return;}const open=event.target.closest('[data-qq-open]');if(open){const message=read().messages.find(item=>item.id===open.dataset.qqOpen);if(message?.link){activeGiftMessage=message;modal.hidden=true;const input=document.getElementById('yinli-gift-link');if(input)input.value=message.link;window.YinliStudio?.openGift(message.link);}return;}const action=event.target.closest('[data-qq-action]')?.dataset.qqAction;if(action==='login'){const name=modal.querySelector('#qq-demo-name')?.value.trim();if(name){const data=read();data.name=name;data.owner||=name;if(save(data)){if(pendingShare){const pending=pendingShare;pendingShare=null;data.messages.push({id:crypto.randomUUID(),from:data.name,to:pending.to,at:Date.now(),text:'我给你送来一份音礼',link:pending.link});save(data);inbox(pending.to);}else inbox();}}}if(action==='share')share();if(action==='send')send();if(action==='record')toggleRecord();if(action==='list')modal.querySelector('.qq-chat-layout')?.classList.remove('show-conversation');});
  document.addEventListener('change',event=>{if(event.target.id==='qq-demo-identity'){const data=read();data.name=event.target.value;save(data);activeContact='';inbox();}});
  document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!modal.hidden)modal.hidden=true;if(event.key==='Enter'&&event.target.id==='qq-demo-name'){event.preventDefault();modal.querySelector('[data-qq-action="login"]')?.click();}if(event.key==='Enter'&&event.target.id==='qq-chat-text'&&!event.shiftKey){event.preventDefault();send();}});
  new MutationObserver(shareBox).observe(document.body,{subtree:true,childList:true});
  const reply=document.createElement('button');reply.id='qq-echo-button';reply.type='button';reply.textContent='留下回声';reply.hidden=true;document.body.append(reply);
  window.addEventListener('yinli-role-change',event=>{reply.hidden=event.detail?.role!=='receiver';});window.addEventListener('yinli-return-landing',()=>{reply.hidden=true;});
})();
